# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_nnpql <- function(y, X, Ks, init_alpha_beta, model, maxIter, tol, lib_size, nngp, nn_mtx, fix_h2eq1, verbose) {
    .Call(`_nnPQL_run_nnpql`, y, X, Ks, init_alpha_beta, model, maxIter, tol, lib_size, nngp, nn_mtx, fix_h2eq1, verbose)
}

